name: Test CI

on:
  pull_request:
  
jobs:
  test-changed-md-files:
    runs-on: ubuntu-16.04
    name: Test changed markdown documentation files.
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: |
          pip install absl-py
          pip freeze all
      - name: Debug information
        run: |
          echo $(git log)
          echo $(git status)
          echo $(git branch)
          echo $(git remote)
          echo $(git diff origin/master --name-only)
      - name: Run mock script changed files
        run: |
          git diff origin/master --name-only | xargs python2.7 ./tools/run-on-files.py
      - name: Run validator on changed files
        run: |
          git diff origin/master --name-only | xargs python2.7 ./tools/validator.py
