name: Test CI

on:
  pull_request:
  
jobs:
  test-changed-md-files:
    runs-on: ubuntu-16.04
    name: Test changed markdown documentation files.
    steps:
      - uses: actions/checkout@v1
      - name: Info
        run: |
          echo $(git diff origin)
      - name: Run on changed files
        run: |
          git diff origin --name-only | xargs ./tools/run-on-files.py
